apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  type: ClusterIP
  ports:
    - port: 80 
      targetPort: 3000
      protocol: TCP
  selector:
    name: grafana