{
 "title": "{7}",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "selecteddeviceid" },
   { "name": "fromtime", "query": "1626361200000" },
   {
    "name": "deviceGroupId",
    "query": "d41ce0c6-2e0f-4c54-b780-7e9789d90f62"
   }
  ]
 },
 "panels": [
  { "title": "Device Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Alerts", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId == '$deviceGroupId'\n| project DeviceGroupName",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Device Locations",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 1 },
   "valueName": "total",
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let deviceGroup=DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId == '$deviceGroupId'\n| mv-expand Data\n| project DeviceGroupId, DeviceId=tostring(Data);\nlet devicetable = DeviceTwin\n| join kind= inner deviceGroup on DeviceId\n| summarize arg_max(TimeStamp, *) by DeviceId\n| where isnotnull(Twin.properties.reported.Latitude) and isnotnull(Twin.properties.reported.Longitude)\n| project DeviceId, latitude=Twin.properties.reported.Latitude, longitude=Twin.properties.reported.Longitude;\nlet alerts = Alerts\n| join kind = inner devicetable on DeviceId\n| where $__timeFilter(TimeStamp)\n| summarize alertsCount=count() by DeviceId;\ndevicetable\n| join kind = leftouter alerts on DeviceId\n| extend metric = iff(isnotnull(alertsCount), alertsCount , 0)\n| project DeviceId, latitude, longitude, metric",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let errorCount = AzureDiagnostics\r\n| where $__timeFilter(TimeGenerated)\r\n| where ResourceProvider == \"MICROSOFT.DEVICES\" and ResourceType == \"IOTHUBS\"\r\n| where Level == \"Error\" and ResultDescription == \"ThrottlingException\"\r\n| count;\r\nerrorCount\r\n| extend iotHubHealth = case(Count <= 3, \"Healthy\", \r\n                       Count <= 10, \"Review\", \r\n                       \"Risk\")\r\n| project iotHubHealth",
      "resource": "/subscriptions/{2}/resourceGroups/{3}/providers/Microsoft.OperationalInsights/workspaces/{4}",
      "resultFormat": "table",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let errorCount = AzureDiagnostics\r\n| where $__timeFilter(TimeGenerated)\r\n| where ResourceProvider == \"MICROSOFT.DOCUMENTDB\"\r\n| where Level == \"Error\" and ResultDescription == \"ThrottlingException\"\r\n| count;\r\nerrorCount\r\n| extend cosmosdbHealth = case(Count <= 3, \"Healthy\", \r\n                       Count <= 10, \"Review\", \r\n                       \"Risk\")\r\n| project cosmosdbHealth",
      "resource": "/subscriptions/{2}/resourceGroups/{3}/providers/Microsoft.OperationalInsights/workspaces/{4}",
      "resultFormat": "table",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let errorCount = FailedIngestion\r\n| where $__timeFilter(TimeGenerated)\r\n| count;\r\nerrorCount\r\n| extend adxHealth = case(Count <= 3, \"Healthy\", \r\n                       Count <= 10, \"Review\", \r\n                       \"Risk\")\r\n| project adxHealth",
      "resource": "/subscriptions/{2}/resourceGroups/{3}/providers/Microsoft.OperationalInsights/workspaces/{4}",
      "resultFormat": "table",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let errorCount = AzureDiagnostics\r\n| where $__timeFilter(TimeGenerated)\r\n| where ResourceProvider == \"MICROSOFT.EVENTHUB\"\r\n| where Level == \"Error\" and ResultDescription == \"ThrottlingException\"\r\n| count;\r\nerrorCount\r\n| extend eventhubHealth = case(Count <= 3, \"Healthy\", \r\n                       Count <= 10, \"Review\", \r\n                       \"Risk\")\r\n| project eventhubHealth",
      "resource": "/subscriptions/{2}/resourceGroups/{3}/providers/Microsoft.OperationalInsights/workspaces/{4}",
      "resultFormat": "table",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "let errorCount = KubePodInventory\r\n| where $__timeFilter(TimeGenerated)\r\n| summarize arg_max(TimeGenerated, *) by ServiceName\r\n| where PodStatus != \"Running\"\r\n| count;\r\nerrorCount\r\n| extend aksHealth = case(Count <= 1, \"Healthy\", \r\n                       Count <= 5, \"Review\", \r\n                       \"Risk\")\r\n| project aksHealth",
      "resource": "/subscriptions/{2}/resourceGroups/{3}/providers/Microsoft.OperationalInsights/workspaces/{4}",
      "resultFormat": "time_series",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    }
   ]
  },
  {
   "title": "Device Insights",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let deviceGroup=DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId == '$deviceGroupId'\n| mv-expand Data\n| project DeviceGroupId, DeviceId=tostring(Data), DeviceGroupName;\nDeviceTwin\n| join kind= inner deviceGroup on DeviceId\n| summarize arg_max(TimeStamp, *) by DeviceId \n| where IsDeleted == false\n| count as Registered;",
     "querySource": "raw"
    },
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Alerts", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let deviceGroup=DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId == '$deviceGroupId'\n| mv-expand Data\n| project DeviceGroupId, DeviceId=tostring(Data), DeviceGroupName;\nTelemetry\n| join kind= inner deviceGroup on DeviceId\n| where TimeStamp >= now()-180s and TimeStamp < now()\n| summarize arg_max(TimeStamp, *) by DeviceId\n| project DeviceId\n| count as Connected",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Devices with Active Telemetry",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let deviceGroup=DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId == '$deviceGroupId'\n| mv-expand Data\n| project DeviceGroupId, DeviceId=tostring(Data), DeviceGroupName;\nTelemetry\n| join kind= inner deviceGroup on DeviceId\n| where $__timeFilter(TimeStamp)\n| summarize arg_max(TimeStamp, *) by DeviceId\n| project DeviceId\n| order by DeviceId asc ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Telemetry",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Telemetry", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "$__timeInterval", "type": "interval" }, "property": { "name": "TimeStamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let deviceGroup=DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId ==  '$deviceGroupId'\n| mv-expand Data\n| project DeviceId=tostring(Data);\nTelemetry\n| join kind= inner \n    deviceGroup\n on DeviceId\n| where iff(isnotnull('$selecteddeviceid') and isnotempty('$selecteddeviceid'), DeviceId == '$selecteddeviceid',1==1) \n| where TimeStamp >= unixtime_milliseconds_todatetime($__to)-30m and TimeStamp < unixtime_milliseconds_todatetime($__to)\n| evaluate bag_unpack(Data)\n| project-away deviceId*, iothub*, _*, messageId*,DeviceId1,Message*\n| order by TimeStamp asc\n| take 5000  ",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Alerts By Device",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Alerts", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let deviceGroup=DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId == '$deviceGroupId'\n| mv-expand Data\n| project DeviceGroupId, DeviceId=tostring(Data);\nAlerts\n| join kind= inner deviceGroup on DeviceId\n| where $__timeFilter(TimeStamp)\n| summarize Count=count() by Device=DeviceId\n| order by Device asc nulls last ",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Alerts By Severity",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Alerts", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let deviceGroup=DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId == '$deviceGroupId'\n| mv-expand Data\n| project DeviceGroupId, DeviceId=tostring(Data);\nAlerts\n| join kind= inner deviceGroup on DeviceId\n| where $__timeFilter(TimeStamp)\n| summarize value=count() by metric=tostring(Data.ruleSeverity)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Alerts By Status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Alerts", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Data.status", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "timeshift": {
       "property": {
        "name": null,
        "type": "string"
       },
       "type": "property"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "let deviceGroup=DeviceGroup\n| summarize arg_max(TimeStamp, *) by DeviceGroupId\n| where DeviceGroupId == '$deviceGroupId'\n| mv-expand Data\n| project DeviceGroupId, DeviceId=tostring(Data);\nAlerts\n| join kind= inner deviceGroup on DeviceId\n| where $__timeFilter(TimeStamp)\n| summarize value=count() by metric=tostring(Data.status)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Device Info - $selecteddeviceid",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "selecteddeviceid"
  },
  {
   "title": "Device Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "AzureDiagnostics\n| where ResourceProvider == \"MICROSOFT.DEVICES\" and ResourceType == \"IOTHUBS\"\n| where TimeGenerated > ago(1d)\n| extend parsed_json = parse_json(properties_s)\n| extend DeviceId = tostring(parsed_json.deviceId)\n| where  isnotempty(DeviceId) and DeviceId == '$selecteddeviceid'\n| extend DeviceOp = strcat(DeviceId, \"-Operation-\",OperationName) \n| distinct TimeGenerated, DeviceOp,DeviceId,ResultType,ResultDescription",
      "resource": "/subscriptions/{2}/resourceGroups/{3}/providers/Microsoft.OperationalInsights/workspaces/{4}",
      "resultFormat": "table",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    }
   ]
  },
  {
   "title": "Device Activity Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "DeviceLogs\n| where isnotempty(DeviceId) and DeviceId == '$selecteddeviceid'\n| where $__timeFilter(TimeStamp)\n| extend parsed_json = parse_json(Data)\n| extend Message = tostring(parsed_json.Message)\n| distinct TimeStamp, Message",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Alerts Of Device - $selecteddeviceid",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Alerts", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Alerts\n| where $__timeFilter(TimeStamp)\n| where DeviceId == '$selecteddeviceid'\n| summarize value=count() by metric=tostring(todynamic(Data).status)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Alerts By Status - $selecteddeviceid",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Alerts", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "1h", "type": "interval" }, "property": { "name": "TimeStamp", "type": "dateTime" }, "type": "groupBy" },
        { "property": { "name": "Data.status", "type": "string" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "DeviceId", "type": "string" }, "reduce": { "name": "count", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "timeshift": {
       "property": {
        "name": null,
        "type": "string"
       },
       "type": "property"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          { "operator": { "name": "==", "value": "$deviceid" }, "property": { "name": "DeviceId", "type": "string" }, "type": "operator" }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "Alerts\n| where $__timeFilter(TimeStamp)\n| where DeviceId == '$selecteddeviceid'\n| summarize count() by bin(TimeStamp, 10m), tostring(todynamic(Data).status)\n| order by TimeStamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Telemetry - $selecteddeviceid",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "database": "{5}",
     "expression": {
      "from": { "property": { "name": "Telemetry", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "interval": { "name": "$__timeInterval", "type": "interval" }, "property": { "name": "TimeStamp", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "", "type": "string" }, "reduce": { "name": "", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "Telemetry\n| where TimeStamp >= unixtime_milliseconds_todatetime($fromtime)-15m and TimeStamp < (iff((unixtime_milliseconds_todatetime($fromtime)+15m) > now(),now(),unixtime_milliseconds_todatetime($fromtime)+15m))\n| where DeviceId == '$selecteddeviceid'\n| evaluate bag_unpack(Data)\n| project-away deviceId*, iothub*, _*, messageId*,Message*\n| order by TimeStamp asc ",
     "querySource": "raw"
    }
   ]
  }
 ]
}