{
 "title": "{9}",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "selecteddeviceid", "query": "Default1" },
   { "name": "fromtime", "query": "1626361200000" },
   {
    "name": "deviceGroupId",
    "query": "d41ce0c6-2e0f-4c54-b780-7e9789d90f62"
   }
  ]
 },
 "panels": [
  { "title": "IoT Hub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Devices/IotHubs",
      "metricName": "totalDeviceCount",
      "metricNamespace": "Microsoft.Devices/IotHubs",
      "resourceGroup": "{3}",
      "resourceName": "{5}",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Devices/IotHubs",
      "metricName": "connectedDeviceCount",
      "metricNamespace": "Microsoft.Devices/IotHubs",
      "resourceGroup": "{3}",
      "resourceName": "{5}",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    }
   ]
  },
  {
   "title": "Number of throttling errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Devices/IotHubs",
      "metricName": "d2c.telemetry.ingress.sendThrottle",
      "metricNamespace": "Microsoft.Devices/IotHubs",
      "resourceGroup": "{3}",
      "resourceName": "{5}",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    }
   ]
  },
  {
   "title": "Jobs Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Devices/IotHubs",
      "metricName": "jobs.completed",
      "metricNamespace": "Microsoft.Devices/IotHubs",
      "resourceGroup": "{3}",
      "resourceName": "{5}",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    },
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
     },
     "azureMonitor": {
      "aggOptions": [],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.Devices/IotHubs",
      "metricName": "jobs.failed",
      "metricNamespace": "Microsoft.Devices/IotHubs",
      "resourceGroup": "{3}",
      "resourceName": "{5}",
      "timeGrain": "auto",
      "timeGrains": [],
      "top": "10"
     },
     "azureResourceGraph": { "resultFormat": "table" },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "{2}"
    }
   ]
  },
  {
   "title": "EventHub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "Microsoft.EventHub/namespaces",
        "metricName": "ServerErrors",
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "resourceGroup": "{3}",
        "resourceName": "{6}",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    },
    {
     "title": "User Errors",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "Microsoft.EventHub/namespaces",
        "metricName": "UserErrors",
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "resourceGroup": "{3}",
        "resourceName": "{6}",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    },
    {
     "title": "Quota Exceeded Error",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "Microsoft.EventHub/namespaces",
        "metricName": "QuotaExceededErrors",
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "resourceGroup": "{3}",
        "resourceName": "{6}",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    },
    {
     "title": "Throttled Requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "metricDefinition": "Microsoft.EventHub/namespaces",
        "metricName": "ThrottledRequests",
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "resourceGroup": "{3}",
        "resourceName": "{6}",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    },
    {
     "title": "Incoming Messages / Entity",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "EntityName", "filter": "*", "operator": "eq" }
        ],
        "metricDefinition": "Microsoft.EventHub/namespaces",
        "metricName": "IncomingMessages",
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "resourceGroup": "{3}",
        "resourceName": "{6}",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    },
    {
     "title": "Outgoing Messages / Entity",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "EntityName", "filter": "*", "operator": "eq" }
        ],
        "metricDefinition": "Microsoft.EventHub/namespaces",
        "metricName": "OutgoingMessages",
        "metricNamespace": "Microsoft.EventHub/namespaces",
        "resourceGroup": "{3}",
        "resourceName": "{6}",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cosmos DB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "RU Consumption / Database",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Maximum",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         3600000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "DatabaseName", "filter": "*", "operator": "eq" }
        ],
        "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
        "metricName": "NormalizedRUConsumption",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "{3}",
        "resourceName": "{7}",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    },
    {
     "title": "Document Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 9, "x": 8, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         300000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "DatabaseName", "filter": "*", "operator": "eq" }
        ],
        "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
        "metricName": "DocumentCount",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "{3}",
        "resourceName": "{7}",
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    },
    {
     "title": "Total Requests / min",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "aggregation": "Count",
        "alias": "{{dimensionvalue}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilter": "*",
        "dimensionFilters": [
         { "dimension": "DatabaseName", "filter": "*", "operator": "eq" }
        ],
        "metricDefinition": "Microsoft.DocumentDB/databaseAccounts",
        "metricName": "TotalRequests",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "{3}",
        "resourceName": "{7}",
        "timeGrain": "PT1M",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    }
   ]
  },
  {
   "title": "AKS pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "AKS Pods",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "appInsights": {
        "dimension": [],
        "metricName": "select",
        "timeGrain": "auto"
       },
       "azureLogAnalytics": {
        "query": "let podTable = KubePodInventory\n| where $__timeFilter(TimeGenerated)\n| where isnotempty(ClusterName)\n| where isnotempty(Namespace)\n| where isnotempty(Computer)\n| where Namespace != \"monitoring\" and Namespace != \"aad-pod-id\" and Namespace != \"kube-system\" \n| summarize arg_max(TimeGenerated, *) by Name\n| project TimeGenerated, PodName=Name, Node=Computer, PodType=ControllerKind, PodStatus, ContainerStatus, ContainerStatusReason, PodRestart=PodRestartCount, PodCreationTimeStamp, ClusterName, Namespace;\nlet clusterTable = KubeNodeInventory\n| where $__timeFilter(TimeGenerated) \n| summarize arg_max(TimeGenerated, *) by ClusterId\n| extend ClusterRegion = tostring(parse_json(Labels)[0].[\"topology.kubernetes.io/region\"])\n| project ClusterId, ClusterName, ClusterRegion;\npodTable\n| join kind=inner clusterTable on ClusterName\n| project PodName, ClusterName, PodStatus, ContainerStatus, ContainerStatusReason, ClusterRegion, Node, Restarts=PodRestart, Age=now()-PodCreationTimeStamp, Namespace, ClusterId, PodCreationTimeStamp, TimeGenerated",
        "resource": "/subscriptions/{2}/resourceGroups/{3}/providers/Microsoft.OperationalInsights/workspaces/{4}",
        "resultFormat": "table",
        "workspace": "7602e0e4-8abe-4030-b1ae-b21e75801d7c"
       },
       "azureMonitor": {
        "aggOptions": [],
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "timeGrain": "auto",
        "timeGrains": [],
        "top": "10"
       },
       "azureResourceGraph": { "resultFormat": "table" },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "{2}"
      }
     ]
    }
   ]
  }
 ]
}