
trigger: none
pool:
  vmImage: ubuntu-latest
variables:
  - template: ../templates/variables-all.yaml
  - name: buildId
    value: build-$(Build.BuildId)
  - name: applicationCode
    value: acsagic
  - name: applicationShortCode
    value: acsagic
  - name: environmentCategory
    value: dev
  - name: subscriptionName
    value: Devops.azure3-Subscription
  - name: aksName
    value: $(applicationCode)-$(aksPartialName)-$(environmentCategory)
  - name: appConfigurationName
    value: $(applicationCode)-$(appConfigurationPartialName)-$(environmentCategory)
  - name: resourceGroupName
    value: $(resourceGroupPartialName)-iot-$(applicationShortCode)-$(environmentCategory)
  - name: storageAccountName
    value: $(applicationCode)$(storageAccountPartialName)$(environmentCategory)
  - name: tableStorageName
    value: pipeline
  - name: tableStoragePartition
    value: test
  - name: tableStorageRowKeyPrefix
    value: "$(buildId):"
  - name: kubernetesNamespaceWasCreatedRowKey
    value: kubernetesNamespaceWasCreated
  - name: mmmIotPlatformServicesHelmChartWasInstalledRowKey
    value: mmmIotPlatformServicesHelmChartWasInstalled
  - name: mmmIotPlatformIngressHelmChartWasInstalledRowKey
    value: mmmIotPlatformIngressHelmChartWasInstalled
  - name: tableStorageAppConfigurationConnectionStringRowKey
    value: appConfigurationConnectionString
  - name: kubernetesNamespace
    value: $(buildId)
  - name: dockerfile
    value: Dockerfile
  - name: helmVersion
    value: $(helmVersion2)
  - name: mmmIotPlatformServicesHelmChartName
    value: mmm-iot-platform-services
  - name: mmmIotPlatformIngressHelmChartName
    value: mmm-iot-platform-ingress
  - name: publishedFilesArtifactName
    value: publishFiles
  - name: functionsArtifactName
    value: functionsFiles
  - name: webuiArtifactName
    value: webuiFiles
  - name: helmInstallTimeoutInSeconds
    value: 1000
  - name: grafanaImage
    value: docker.io/azureiot3m/grafana-custom:latest    
  - name: mmmIotPlatformServicesHelmChartValuesFile
    value: pipelines/ci/mmm-iot-platform-chart-values.yaml
  - name: mmmIotPlatformServicesHelmChartReleaseName
    value: services-$(buildId)
  - name: mmmIotPlatformIngressHelmChartReleaseName
    value: ingress-$(buildId)
  - name: commitsSinceLastReleaseArtifactName
    value: commitsSinceLastRelease 
  
stages:
  - stage: build
    displayName: Build
    dependsOn: []
    jobs:
      - job: preBuild
        displayName: Pre-build
        steps:
          - checkout: none

          - task: AzureCLI@2
            displayName: Get App Configuration connection string
            name: getAppConfigurationConnectionString
            inputs:
              azureSubscription: $(subscriptionName)
              scriptType: pscore
              scriptLocation: inlineScript
              inlineScript: |-
                $appConfigurationConnectionString = "Endpoint=https://acshyd-appconfig-dev.azconfig.io;Id=GYCS-l4-s0:MFR+WNIgDpva5VAfDYPP;Secret=hc1mnHRNECprwxNlBi2WwftqQizq19Gi9dyReLf+P6E="
                echo "##vso[task.setvariable variable=AppConfigurationConnectionString;isOutput=true]$appConfigurationConnectionString"

      - job: codeQl
        displayName: Code Scanning using CodeQL
        pool:
          vmImage: windows-latest
        dependsOn:
          - preBuild
        variables:
          AppConfigurationConnectionString: $[dependencies.preBuild.outputs['getAppConfigurationConnectionString.appConfigurationConnectionString']]
        steps:
          - checkout: self
            displayName: Checkout repository

          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '3.1.x'
              includePreviewVersions: true

          - task: CmdLine@1
            displayName: Initialize CodeQL database
            inputs:
                # Assumes the source code is checked out to the current working directory.
                # Creates a database at `/codeql-dbs/example-repo`.
                # Running on Windows, so specifies a trace process level.
                script: "codeql database init --language csharp --trace-process-name Agent.Worker.exe --source-root . --begin-tracing /codeql-dbs/example-repo"

          # For CodeQL to trace future build steps without knowing the explicit build commands,
          # it requires certain environment variables to be set during the build.
          # Read these generated environment variables and values, and set them so they are available for subsequent commands
          # in the build pipeline. This is done in PowerShell in this example.
          - task: PowerShell@1
            displayName: Set CodeQL environment variables
            inputs:
                targetType: inline
                script: >
                  $json = Get-Content /codeql-dbs/example-repo/temp/tracingEnvironment/start-tracing.json | ConvertFrom-Json
                  $json.PSObject.Properties | ForEach-Object {
                      $template = "##vso[task.setvariable variable="
                      $template += $_.Name
                      $template += "]"
                      $template += $_.Value
                      echo "$template"
                  }

          # Execute the pre-defined build step. Note the `msbuildArgs` variable.
          - task: VSBuild@1
              inputs:
                solution: '**/*.sln'
                # Disable MSBuild shared compilation for C# builds.
                msbuildArgs: /p:OutDir=$(Build.ArtifactStagingDirectory) /p:UseSharedCompilation=false
                platform: Any CPU
                configuration: Release
                # Execute a clean build, in order to remove any existing build artifacts prior to the build.
                clean: True
            displayName: Visual Studio Build

          # Read and set the generated environment variables to end build tracing. This is done in PowerShell in this example.
          - task: PowerShell@1
            displayName: Clear CodeQL environment variables
            inputs:
                targetType: inline
                script: >
                  $json = Get-Content $(System.DefaultWorkingDirectory)/db/temp/tracingEnvironment/end-tracing.json | ConvertFrom-Json
                  $json.PSObject.Properties | ForEach-Object {
                      $template = "##vso[task.setvariable variable="
                      $template += $_.Name
                      $template += "]"
                      $template += $_.Value
                      echo "$template"
                  }

          # Use `codeql database finalize` to complete database creation after the build is done.
          - task: CmdLine@2
            displayName: Finalize CodeQL database
            inputs:
                script: 'codeql database finalize /codeql-dbs/example-repo'

          # Analyze the database and upload the results.
          - task: CmdLine@2
            displayName: Analyze CodeQL database
            inputs:
                script: 'codeql database analyze /codeql-dbs/example-repo csharp-code-scanning.qls --sarif-category=csharp --format=sarif-latest --output=/temp/example-repo-csharp.sarif'

          - task: CmdLine@2
            displayName: Upload CodeQL results
            inputs:
                script: 'echo "$(GITHUB_PAT_TOKEN)" | codeql github upload-results --repository=tangirala-aditya/azure-iot-platform-dotnet \
              --ref $(Build.SourceVersion) --ref $(Build.SourceBranch) \
              --sarif=/temp/example-repo-csharp.sarif --github-auth-stdin'

                    # - script: |
                    #     wget https://github.com/github/codeql-action/releases/latest/download/codeql-runner-linux
                    #     chmod +x codeql-runner-linux
                    #   displayName: 'Get latest CodeQL package. Install on Agent.'

                    # - script: |
                    #     ./codeql-runner-linux init  --languages csharp --repository tangirala-aditya/azure-iot-platform-dotnet --github-url https://github.com --github-auth $(GITHUB_PAT_TOKEN)
                    #   displayName: 'Get latest CodeQL package. Install on Agent.'

          - script: >-
              dotnet restore
              --force
              --no-cache
              --no-dependencies
              --packages .nuget
              --runtime $(dotnetProductionRuntimeId)
              /p:TargetLatestRuntimePatch=true
              /p:OutDir=$(Build.ArtifactStagingDirectory) 
              /p:UseSharedCompilation=false
            displayName: Restore dependencies

          - script: >-
              dotnet publish
              --self-contained false
              --no-restore
              --no-dependencies
              --configuration $(dotnetBuildConfiguration)
              --runtime $(dotnetProductionRuntimeId)
              /p:TargetLatestRuntimePatch=true
              /p:OutDir=$(Build.ArtifactStagingDirectory)
              /p:UseSharedCompilation=false
            displayName: Build assemblies

          - script: |
                ./codeql-runner-linux analyze --repository tangirala-aditya/azure-iot-platform-dotnet --github-url https://github.com --github-auth $(GITHUB_PAT_TOKEN) --commit $(Build.SourceVersion) --ref $(Build.SourceBranch)
            displayName: 'CodeQL Analyse'
