apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    name: grafana
spec:
  type: ClusterIP
  ports:
    - port: 8000 
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: grafana
